#define XBOX_CONTROLLER false
#define IMU false

#define WHEEL_RADIUS 0.08f

#define LEFT_MASTER_GEARBOX_MOTOR_CAN_ID 2
#define LEFT_SLAVE_GEARBOX_MOTOR_CAN_ID 3
#define RIGHT_MASTER_GEARBOX_MOTOR_CAN_ID 1
#define RIGHT_SLAVE_GEARBOX_MOTOR_CAN_ID 4

#define LEFT_SHOOTER_FALCON_CAN_ID 5
#define RIGHT_SHOOTER_FALCON_CAN_ID 6
